export const categories = [
  { path: "men_tshirts", gender: "Men", category: "T-Shirts" },
  {
    path: "men_shortsleevebuttons",
    gender: "Men",
    category: "Short Sleeve Button Ups",
  },
  { path: "men_sweatshirts", gender: "Men", category: "Sweatshirts" },
  { path: "men_longsleevebuttons", gender: "Men", category: "Button Ups" },
  { path: "men_jackets", gender: "Men", category: "Jackets" },
  { path: "men_shorts", gender: "Men", category: "Shorts" },
  { path: "men_jeans", gender: "Men", category: "Jeans" },
  { path: "men_pants", gender: "Men", category: "Pants" },
  { path: "women_tshirts", gender: "Women", category: "T-Shirts" },
  { path: "women_sweatshirts", gender: "Women", category: "Sweatshirts" },
  { path: "women_longsleeves", gender: "Women", category: "Long Sleeves" },
  { path: "women_jackets", gender: "Women", category: "Jackets" },
  { path: "women_shorts", gender: "Women", category: "Shorts" },
  { path: "women_jeans", gender: "Women", category: "Jeans" },
  { path: "women_pants", gender: "Women", category: "Pants" },
  { path: "women_croptops", gender: "Women", category: "Crop Tops" },
  { path: "women_dresses", gender: "Women", category: "Dresses" },
  { path: "women_skirts", gender: "Women", category: "Skirts" },
  { path: "women_bras", gender: "Women", category: "Bras" },
  { path: "women_sportbras", gender: "Women", category: "Sportbras" },
];

export const brands = [
  "Nike",
  "Adidas",
  "Lowkey",
  "American Eagle",
  "Hollister",
  "Burberry",
];
